def parse_recipe(recipe_text):
    """Parses the recipe text generated by GPT to extract relevant fields except Meal_ID."""
    recipe = {}
    lines = recipe_text.split("\n")
    
    ingredient_lines = []  # to collect ingredient lines
    collecting_ingredients = False

    for line in lines:
        if ":" in line:
            key, value = line.split(":", 1)
            key = key.strip()
            value = value.strip().replace("kcal", "").replace("~", "").strip()  # Removing unwanted characters
        else:
            if collecting_ingredients:
                ingredient_lines.append(line.strip('- '))
            continue

        if key == "Ingredients":
            collecting_ingredients = True
            continue
        elif key in ["Meal Name", "Calories", "Protein", "Carbs", "Fats", "Meal_Type"]:
            collecting_ingredients = False
            recipe[key] = value

    recipe["Ingredients"] = ", ".join(ingredient_lines)  # converting ingredient list to a string

    # Check if all the essential keys (excluding Meal_ID) are present; if not, return None
    essential_keys = ["Meal Name", "Calories", "Protein", "Carbs", "Fats", "Ingredients", "Meal_Type"]
    missing_keys = [key for key in essential_keys if key not in recipe]
    
    if missing_keys:
        print(f"Missing keys: {missing_keys}")
        return None

    return recipe
